In [1]:
# Financial Data Exploration & Insights

In [2]:
#Import Libraries 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
#Load financial Dataset
df = pd.read_csv("guided_financial_practical_lab.csv")

In [4]:
# Display the first five record
df.head()

,Transaction_ID,Date,Department,Region,Transaction_Type,Payment_Method,Account_Type,Description,Amount,Annual_Budget
0,FIN10458,2025-05-05,Finance,Abuja,Income,Direct Debit,Savings Account,Software Subscription,522414.0,9000000.0
1,FIN10749,2025-07-04,Sales,Lagos,Expense,Bank Transfer,Current Account,Salary,484955.0,16000000.0
2,FIN10705,2025-04-26,Human Resources,Ibadan,Expense,Cash,Business Account,Advertising,466413.0,10000000.0
3,FIN11299,2025-12-21,Finance,Ibadan,Income,Bank Transfer,Savings Account,Travel,101755.0,9000000.0
4,FIN11395,2025-01-06,Finance,Abuja,Income,Mobile Money,Business Account,Service Fee,788740.0,9000000.0

In [5]:
# Check the dataset size
df.shape

(1620, 10)

In [6]:
# Check the colunm names
df.columns

Index(['Transaction_ID', 'Date', 'Department', 'Region', 'Transaction_Type',
       'Payment_Method', 'Account_Type', 'Description', 'Amount',
       'Annual_Budget'],
      dtype='str')

In [7]:
# Inspect the dataset
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1620 entries, 0 to 1619
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction_ID    1620 non-null   str
 1   Date              1620 non-null   str
 2   Department        1620 non-null   str
 3   Region            1598 non-null   str
 4   Transaction_Type  1620 non-null   str
 5   Payment_Method    1620 non-null   str
 6   Account_Type      1620 non-null   str
 7   Description       1605 non-null   str
 8   Amount            1601 non-null   float64
 9   Annual_Budget     1620 non-null   float64
dtypes: float64(2), str(8)
memory usage: 244.8 KB

In [8]:
#Generate statistics
df.describe()

             Amount  Annual_Budget
count  1.601000e+03   1.620000e+03
mean   6.383666e+05   1.316728e+07
std    4.761403e+05   3.249523e+06
min    2.108900e+04   9.000000e+06
25%    2.692090e+05   1.000000e+07
50%    4.926440e+05   1.200000e+07
75%    9.370710e+05   1.600000e+07
max    1.799319e+06   1.800000e+07

In [9]:
# confirm the missing value
df.isnull().sum()

Transaction_ID       0
Date                 0
Department           0
Region              22
Transaction_Type     0
Payment_Method       0
Account_Type         0
Description         15
Amount              19
Annual_Budget        0
dtype: int64

In [10]:
# Calculate missing value percentage
Missing_value_percentage = (df.isnull().sum() /len(df)) * 100
print (Missing_value_percentage)

Transaction_ID      0.000000
Date                0.000000
Department          0.000000
Region              1.358025
Transaction_Type    0.000000
Payment_Method      0.000000
Account_Type        0.000000
Description         0.925926
Amount              1.172840
Annual_Budget       0.000000
dtype: float64

In [19]:
# Decide how to handle each missing values
df["Region"] = df["Region"].fillna ("Unknown")

In [20]:
# Decide how to handle each missing values
df["Description"] = df["Description"].fillna ("Unknown")

In [26]:
# Decide how to handle each missing values
df["Amount"] = df["Amount"].fillna(df["Amount"].median())

In [27]:
# Verify the cleaning
df.isnull().sum()

Transaction_ID      0
Date                0
Department          0
Region              0
Transaction_Type    0
Payment_Method      0
Account_Type        0
Description         0
Amount              0
Annual_Budget       0
dtype: int64

In [35]:
# check for duplicates
df.duplicated().sum()

np.int64(20)

In [39]:
#drop duplicates
df=df.drop_duplicates()

In [40]:
# check for duplicates again
df.duplicated().sum()

np.int64(0)

In [41]:
# check the clean dataset
df.info()

<class 'pandas.DataFrame'>
Index: 1600 entries, 0 to 1619
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction_ID    1600 non-null   str
 1   Date              1600 non-null   str
 2   Department        1600 non-null   str
 3   Region            1600 non-null   str
 4   Transaction_Type  1600 non-null   str
 5   Payment_Method    1600 non-null   str
 6   Account_Type      1600 non-null   str
 7   Description       1600 non-null   str
 8   Amount            1600 non-null   float64
 9   Annual_Budget     1600 non-null   float64
dtypes: float64(2), str(8)
memory usage: 255.5 KB

In [50]:
# save a cleaned csv
df.to_csv("Financial_lab_cleaned_dataset.csv",index=False)

In [ ]:
### check the dataset info again using df.head(),df.shape,df.describe()

In [54]:
# check the dataset info
df.head()

,Transaction_ID,Date,Department,Region,Transaction_Type,Payment_Method,Account_Type,Description,Amount,Annual_Budget
0,FIN10458,2025-05-05,Finance,Abuja,Income,Direct Debit,Savings Account,Software Subscription,522414.0,9000000.0
1,FIN10749,2025-07-04,Sales,Lagos,Expense,Bank Transfer,Current Account,Salary,484955.0,16000000.0
2,FIN10705,2025-04-26,Human Resources,Ibadan,Expense,Cash,Business Account,Advertising,466413.0,10000000.0
3,FIN11299,2025-12-21,Finance,Ibadan,Income,Bank Transfer,Savings Account,Travel,101755.0,9000000.0
4,FIN11395,2025-01-06,Finance,Abuja,Income,Mobile Money,Business Account,Service Fee,788740.0,9000000.0

In [55]:
df.shape

(1600, 10)

In [56]:
df.describe()

             Amount  Annual_Budget
count  1.600000e+03   1.600000e+03
mean   6.364676e+05   1.317750e+07
std    4.737996e+05   3.247320e+06
min    2.108900e+04   9.000000e+06
25%    2.704000e+05   1.000000e+07
50%    4.926440e+05   1.200000e+07
75%    9.228122e+05   1.600000e+07
max    1.799319e+06   1.800000e+07

In [57]:
df.isnull().sum()

Transaction_ID      0
Date                0
Department          0
Region              0
Transaction_Type    0
Payment_Method      0
Account_Type        0
Description         0
Amount              0
Annual_Budget       0
dtype: int64

In [58]:
### Financial Descriptive Statistics

In [70]:
#Describe a colunm
df["Amount"].describe()

count    1.600000e+03
mean     6.364676e+05
std      4.737996e+05
min      2.108900e+04
25%      2.704000e+05
50%      4.926440e+05
75%      9.228122e+05
max      1.799319e+06
Name: Amount, dtype: float64

In [82]:
# Calculate Average Transaction
df["Amount"].mean()

np.float64(636467.6075)

In [83]:
df["Amount"].median()

np.float64(492644.0)

In [84]:
df["Amount"].max()

np.float64(1799319.0)

In [85]:
df["Amount"].min()

np.float64(21089.0)

In [95]:
Total_Amount = df["Amount"]. sum()

In [96]:
print (Total_Amount)

1018348172.0

In [98]:
# Analzye income vs expenses
df["Transaction_Type"].value_counts()

Transaction_Type
Income     831
Expense    769
Name: count, dtype: int64

In [113]:
# Calculate total income
Total_Income = df[df["Transaction_Type"]=="Income"]["Amount"].sum()

In [114]:
print(Total_Income)

758793898.0

In [115]:
# Calculate total income
Total_Expense = df[df["Transaction_Type"]=="Expense"]["Amount"].sum()

In [116]:
print(Total_Expense)

259554274.0

In [117]:
#calculate the net cash flow
Net_cash_flow = Total_Income-Total_Expense

In [119]:
print(Net_cash_flow)
# If it is positive, it means the Income is greter than the Expenses but if it is negative the Expenses is gretater than the income

499239624.0

In [120]:
# Calculate the Income to Expenses Ratio 
Total_Income/Total_Expense

np.float64(2.9234498292253126)

In [121]:
# Create a financial Summary

In [128]:
Financial_Summary= pd.DataFrame({"Metrics":["Total_Income","Total_Expense","Net_cash_flow",
                                           "Average_Transaction","Maximun_Transaction","Minimum_Transaction"],
                                 "Amount":[Total_Income,Total_Expense,Net_cash_flow,
                                           df["Amount"].mean(),
                                           df["Amount"].max(),
                                           df["Amount"].min()
                                          ]})

In [129]:
print(Financial_Summary)

               Metrics        Amount
0         Total_Income  7.587939e+08
1        Total_Expense  2.595543e+08
2        Net_cash_flow  4.992396e+08
3  Average_Transaction  6.364676e+05
4  Maximun_Transaction  1.799319e+06
5  Minimum_Transaction  2.108900e+04

In [131]:
#Analyze Transaction by Department
Department_Amount=df.groupby("Department")["Amount"].sum()

In [132]:
#Analyze Transaction by Department
Department_Amount.sort_values(ascending=False)

Department
Finance            200839134.0
Sales              183262662.0
Marketing          180901528.0
Human Resources    155774592.0
Operations         151699015.0
IT                 145871241.0
Name: Amount, dtype: float64

In [136]:
#Analyze  Income and Expenses by Department

Department_Type=df.groupby(["Department","Transaction_Type"])["Amount"].sum()

In [137]:
#You can make it easier to read by doing this
Department_Type.unstack()

Transaction_Type     Expense       Income
Department
Finance           46227980.0  154611154.0
Human Resources   40707992.0  115066600.0
IT                35684232.0  110187009.0
Marketing         52161472.0  128740056.0
Operations        41854414.0  109844601.0
Sales             42918184.0  140344478.0

In [152]:
#Financial Activity by Region sort in Ascending order

Region_Amount=df.groupby("Region")["Amount"].sum()

In [153]:
Region_Amount.sort_values(ascending=False)

Region
Lagos            215796668.0
Abuja            207240407.0
Ibadan           202835689.0
Port Harcourt    194785860.0
Kano             184361274.0
Unknown           13328274.0
Name: Amount, dtype: float64

In [154]:
# Analyze Payment_Method
df["Payment_Method"].value_counts()

Payment_Method
Card             347
Direct Debit     324
Bank Transfer    315
Mobile Money     310
Cash             304
Name: count, dtype: int64

In [156]:
Payment_Amount=df.groupby("Payment_Method")["Amount"].sum()

In [157]:
Payment_Amount.sort_values(ascending=False)

Payment_Method
Card             227109234.0
Direct Debit     206245157.0
Bank Transfer    197407523.0
Cash             196854669.0
Mobile Money     190731589.0
Name: Amount, dtype: float64